"""
PPTX -> Touying emitter: orchestration and calibration.

Two emission styles share the shape-dispatch logic:

- **probed / absolute** (default): every shape is placed at its absolute
  PPTX coordinates on a page equal to the PPTX slide size (margin 0), so
  PPTX pt coordinates map 1:1 to Typst pt coordinates and every element
  carries a ``tp-probe`` for Method-B verification. This is the mode the
  verification loop gates on.
- **minimal** (``minimal=True``): human-editable output without probes,
  intended for people who continue editing the .typ file (see
  :mod:`typstpresenter.convert.flow`).

After the first write, a calibration loop measures the laid-out content via
the probes (like PowerPoint does at edit time) and iterates: it shrinks
autofit text until it fits its box and corrects per-slide CeTZ canvas drift
caused by ink that extends beyond the page.
"""

from __future__ import annotations

from dataclasses import replace
from pathlib import Path

import pptx

from typstpresenter.convert.cetz import emit_cetz_shape, is_diagram_shape
from typstpresenter.convert.faults import Fault
from typstpresenter.convert.markup import escape_typst
from typstpresenter.convert.media import emit_picture, emit_table
from typstpresenter.convert.pptx_inherit import resolve_autofit
from typstpresenter.convert.textbody import emit_text_body
from typstpresenter.verify.geometry import EMU_PER_PT, BBox
from typstpresenter.verify.method_b import PROBE_PRELUDE
from typstpresenter.verify.pptx_geometry import (
    element_id,
    is_picture,
    iter_flat_shapes,
)

TOUYING_VERSION = "0.6.1"
CETZ_VERSION = "0.5.2"


def shape_bbox(shape) -> BBox | None:
    if shape.left is None or shape.top is None:
        return None
    return BBox(
        shape.left / EMU_PER_PT,
        shape.top / EMU_PER_PT,
        (shape.width or 0) / EMU_PER_PT,
        (shape.height or 0) / EMU_PER_PT,
    )


def slide_title_text(slide) -> str:
    if slide.shapes.title and slide.shapes.title.has_text_frame:
        # \x0b is python-pptx's rendering of an in-paragraph line break
        text = slide.shapes.title.text.strip()
        return " ".join(text.replace("\x0b", " ").replace("\n", " ").split())
    return ""


def emit_touying(
    pptx_path: Path | str,
    out_path: Path | str,
    probes: bool = True,
    faults: tuple[Fault, ...] = (),
    default_font_size: float = 18.0,
    minimal: bool = False,
) -> Path:
    """
    Emit a Touying presentation from a PPTX file.

    With ``probes=True`` every text/image element becomes a
    ``tp-probe(...)`` call (designed geometry included) and
    autoshapes/connectors become one CeTZ canvas per slide with
    ``tp-node-probe`` markers. ``minimal=True`` disables probes and emits
    human-editable output instead.
    """
    pptx_path = Path(pptx_path)
    out_path = Path(out_path)
    if minimal:
        return emit_minimal(pptx_path, out_path, default_font_size)
    prs = pptx.Presentation(str(pptx_path))
    page_w = prs.slide_width / EMU_PER_PT
    page_h = prs.slide_height / EMU_PER_PT
    faults_by_id = {f.element_id: f for f in faults}

    header = [
        "// Auto-generated by typstpresenter baseline emitter -- edit freely.",
        f'#import "@preview/touying:{TOUYING_VERSION}": *',
        "#import themes.simple: *",
        f'#import "@preview/cetz:{CETZ_VERSION}"',
        "",
        "#show: simple-theme.with(",
        f"  config-page(width: {page_w:g}pt, height: {page_h:g}pt, margin: 0pt),",
        "  config-common(handout: true),",
        "  header: none,",
        "  footer: none,",
        ")",
        '#set text(font: ("Calibri", "Arial", "Liberation Sans"))',
        # PPTX text is literal; PowerPoint does not substitute quotes at render
        "#set smartquote(enabled: false)",
        "",
    ]
    if probes:
        header.append(PROBE_PRELUDE)

    media_dir = out_path.parent / f"{out_path.stem}_media"
    # elements whose bodyPr requests shrink-on-overflow; PowerPoint computes
    # the actual fontScale at edit time, so we must derive it ourselves
    autofit_ids: set[str] = set()
    # label probe id -> (slide, expected label center x, expected anchor y,
    # anchor kind); used to measure and correct per-slide canvas drift
    label_expect: dict[str, tuple] = {}

    def build_body(shrink: dict[str, float],
                   canvas_adjust: dict[int, tuple[float, float]]) -> list[str]:
        body: list[str] = []
        for slide_index, slide in enumerate(prs.slides):
            body.append("== ")

            cetz_lines: list[str] = []
            # shapes parked outside the slide inflate the canvas bounds and
            # would shift the whole canvas; track the overhang to compensate
            overhang_left = overhang_top = 0.0
            for shape, bbox in iter_flat_shapes(slide.shapes):
                eid = element_id(slide_index, shape.shape_id)
                fault = faults_by_id.get(eid)
                if fault:
                    if fault.drop:
                        continue
                    bbox = replace(
                        bbox,
                        x=bbox.x + fault.dx, y=bbox.y + fault.dy,
                        w=bbox.w * fault.scale_w, h=bbox.h * fault.scale_h,
                    )

                if is_diagram_shape(shape):
                    markup, expectation = emit_cetz_shape(shape, eid, bbox, probes)
                    cetz_lines.append(markup)
                    if expectation is not None:
                        label_expect[eid] = (slide_index, *expectation)
                    overhang_left = min(overhang_left, bbox.x)
                    overhang_top = min(overhang_top, bbox.y)
                    continue

                if getattr(shape, "has_table", False):
                    content = emit_table(shape, default_font_size)
                elif is_picture(shape):
                    media_dir.mkdir(parents=True, exist_ok=True)
                    content = emit_picture(shape, eid, media_dir)
                elif shape.has_text_frame and shape.text_frame.text.strip():
                    if resolve_autofit(shape) == "shrink":
                        autofit_ids.add(eid)
                    content = emit_text_body(
                        shape, default_size=default_font_size,
                        extra_text=fault.extra_text if fault else "",
                        extra_scale=shrink.get(eid, 1.0),
                    )
                else:
                    continue

                geometry = f"{bbox.x:.2f}pt, {bbox.y:.2f}pt, {bbox.w:.2f}pt, {bbox.h:.2f}pt"
                if probes:
                    body.append(f'  #tp-probe("{eid}", {geometry})[\n{content}\n  ]')
                else:
                    body.append(
                        f"  #place(top + left, dx: {bbox.x:.2f}pt, dy: {bbox.y:.2f}pt, "
                        f"block(width: {bbox.w:.2f}pt, height: {bbox.h:.2f}pt)[\n{content}\n  ])"
                    )

            if cetz_lines:
                adjust_x, adjust_y = canvas_adjust.get(slide_index, (0.0, 0.0))
                body.append(
                    f"  #place(top + left, dx: {overhang_left + adjust_x:.2f}pt, "
                    f"dy: {overhang_top + adjust_y:.2f}pt, cetz.canvas(length: 1pt, {{"
                )
                body.append("    import cetz.draw: *")
                body.append("    set-style(stroke: 0.75pt)")
                # invisible full-page rect anchors the canvas at the page
                # origin, otherwise CeTZ shrink-wraps it and everything shifts
                body.append(f"    rect((0, 0), ({page_w:.2f}, {-page_h:.2f}), stroke: none)")
                body.append("\n".join(cetz_lines))
                body.append("  }))")
            body.append("")
        return body

    shrink: dict[str, float] = {}
    canvas_adjust: dict[int, tuple[float, float]] = {}

    def write() -> None:
        out_path.write_text(
            "\n".join(header + build_body(shrink, canvas_adjust)),
            encoding="utf-8", newline="\n",
        )

    write()

    # Calibration: like PowerPoint at edit time, measure the laid-out content
    # via the probes and (a) shrink autofit text until it fits its box,
    # (b) correct per-slide canvas drift caused by labels or shapes whose
    # ink extends beyond the page (cetz sizes the canvas to its content).
    if probes and (autofit_ids or label_expect):
        from typstpresenter.verify.typst_tools import query

        # many-paragraph autofit bodies respond sub-linearly to font scale
        # (minimum one line per paragraph), so convergence can take ~10 rounds
        for _ in range(14):
            measured = query(out_path, "<tp-probe>").value

            needed = {
                p["id"]: p["h"] / p["content-h"]
                for p in measured
                if "w" in p and p["id"] in autofit_ids
                and p["content-h"] > p["h"] + 0.5
            }
            for eid, ratio in needed.items():
                # extra 3% margin compounds across rounds, absorbing the
                # sub-linear response of reflowing text
                shrink[eid] = shrink.get(eid, 1.0) * ratio * 0.97

            drift: dict[int, list[tuple[float, float]]] = {}
            for p in measured:
                expect = label_expect.get(p["id"])
                if expect is None or "label-h" not in p:
                    continue
                slide_index, expect_cx, expect_y, kind = expect
                measured_cx = p["x"] + p["label-w"] / 2
                if kind == "north":
                    measured_y = p["y"]
                elif kind == "south":
                    measured_y = p["y"] + p["label-h"]
                else:
                    measured_y = p["y"] + p["label-h"] / 2
                drift.setdefault(slide_index, []).append(
                    (measured_cx - expect_cx, measured_y - expect_y))
            adjusted = False
            for slide_index, deltas in drift.items():
                dxs = sorted(d[0] for d in deltas)
                dys = sorted(d[1] for d in deltas)
                dx, dy = dxs[len(dxs) // 2], dys[len(dys) // 2]
                if abs(dx) > 0.5 or abs(dy) > 0.5:
                    prev = canvas_adjust.get(slide_index, (0.0, 0.0))
                    canvas_adjust[slide_index] = (prev[0] - dx, prev[1] - dy)
                    adjusted = True

            if not needed and not adjusted:
                break
            write()

    return out_path


def emit_minimal(
    pptx_path: Path | str,
    out_path: Path | str,
    default_font_size: float = 18.0,
    calibrate: bool = True,
) -> Path:
    """
    Emit a human-editable Touying presentation (flow mode, no probes).

    Flowing content has no fixed boxes, so instead of PPTX autofit a
    page-based calibration shrinks slides that spill onto extra pages:
    the document is emitted with temporary invisible slide markers,
    ``typst query`` reports the page each slide starts on, and slides
    spanning several pages get a font scale below 1. The final document
    is written without markers.
    """
    from typstpresenter.convert.flow import (
        PAGE_MARGIN_BOTTOM,
        PAGE_MARGIN_TOP,
        PAGE_MARGIN_X,
        deck_title_size,
        document_body_size,
        flow_slide_markup,
    )
    from typstpresenter.verify.typst_tools import TypstError, query

    pptx_path = Path(pptx_path)
    out_path = Path(out_path)
    prs = pptx.Presentation(str(pptx_path))
    page_w = prs.slide_width / EMU_PER_PT
    page_h = prs.slide_height / EMU_PER_PT
    media_dir = out_path.parent / f"{out_path.stem}_media"
    doc_size = document_body_size(prs, default_font_size)
    title_size = deck_title_size(prs)
    slide_count = len(prs.slides._sldIdLst)

    def write(scales: dict[int, float], markers: bool) -> None:
        body: list[str] = []
        for slide_index, slide in enumerate(prs.slides):
            body += flow_slide_markup(
                slide, slide_index, page_w, page_h, media_dir,
                default_font_size, doc_size,
                scale=scales.get(slide_index, 1.0),
                calibration_marker=markers,
                heading_size=title_size,
            )
        if markers:
            # sentinel at document end: gives the last slide's page span
            body.append(f"#place(hide(context metadata((s: {slide_count}, "
                        "p: here().position().page))))")
        body_text = "\n".join(body)
        header = [
            "// Generated by typstpresenter -- edit freely.",
            f'#import "@preview/touying:{TOUYING_VERSION}": *',
            "#import themes.simple: *",
        ]
        if "cetz." in body_text:
            header.append(f'#import "@preview/cetz:{CETZ_VERSION}"')
        header += [
            "",
            "#show: simple-theme.with(",
            f"  config-page(width: {page_w:g}pt, height: {page_h:g}pt,"
            f" margin: (x: {PAGE_MARGIN_X:g}pt, top: {PAGE_MARGIN_TOP:g}pt,"
            f" bottom: {PAGE_MARGIN_BOTTOM:g}pt)),",
            "  config-common(handout: true),",
        ]
        if title_size is not None:
            # slide headings at the deck's resolved title size (the theme
            # default is a mere 1.2em of the body text)
            header.append(
                f"  subslide-preamble: block(below: 0.8em, "
                f'text({title_size:g}pt, weight: "bold", '
                "utils.display-current-heading(level: 2))),")
        header += [
            ")",
            '#set text(font: ("Calibri", "Arial", "Liberation Sans"),'
            f" size: {doc_size:g}pt)",
            # PPTX text is literal; PowerPoint does not substitute quotes
            "#set smartquote(enabled: false)",
            "",
        ]
        out_path.write_text("\n".join(header) + "\n" + body_text,
                            encoding="utf-8", newline="\n")

    scales: dict[int, float] = {}
    if calibrate:
        for _ in range(9):
            write(scales, markers=True)
            try:
                marks = query(out_path, "metadata").value
            except TypstError:
                break  # calibration must never block emission
            # touying uses metadata internally; ours carry "s" and "p"
            start_page: dict[int, int] = {}
            for m in marks:
                if isinstance(m, dict) and "s" in m and "p" in m:
                    s, p = m["s"], m["p"]
                    start_page[s] = min(start_page.get(s, p), p)
            spans: dict[int, int] = {}
            for s, p in start_page.items():
                if s == slide_count:
                    continue
                nxt = start_page.get(s + 1)
                if nxt is None:
                    continue
                # the sentinel (s == slide_count) sits on the last slide's
                # final page, not on a page of its own
                spans[s] = (nxt - p) if s + 1 < slide_count else (nxt - p + 1)
            changed = False
            for s, span in spans.items():
                if span > 1:
                    # gentle steps: coarse factors overshoot and leave
                    # slides much smaller than they need to be
                    factor = 0.9 if span == 2 else 0.72
                    scales[s] = max(scales.get(s, 1.0) * factor, 0.4)
                    changed = True
            if not changed:
                break
    write(scales, markers=False)
    return out_path
